development: &default
  adapter: postgresql
  database: raffleboard_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  user: djcp

test:
  <<: *default
  database: raffleboard_test
